---
name: "release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/checkout@v3
      - run: pnpm install
      - run: pnpm -F ui build
      - run: pnpm -F build build
      - name: "release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            packages/build/pickle.user.js
