---
name: "release"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: pnpm install
      - run: pnpm -F ui build
      - run: pnpm -F build build
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages/build/pickle.user.js
